apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: foslliher-python
  janus-idp.io/tekton: foslliher-python
  backstage.io/kubernetes-id: foslliher-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: foslliher-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
